# =====================================
# BOBBY AI STUDIO v2.8
# Workflow Automation System
# =====================================

import json
import os
from datetime import datetime

import stories
import prompts
import files


WORKFLOW_FILE = "data/workflows.json"


def create_folder():

    if not os.path.exists("data"):
        os.makedirs("data")



def save_workflow(name, steps):

    create_folder()

    workflow = {

        "name": name,
        "steps": steps,
        "created": str(datetime.now())

    }


    try:

        with open(WORKFLOW_FILE, "r") as f:
            data = json.load(f)

    except:

        data = []


    data.append(workflow)


    with open(WORKFLOW_FILE, "w") as f:

        json.dump(data, f, indent=4)


    print("✅ Workflow Saved Successfully!")



def view_workflows():

    create_folder()

    try:

        with open(WORKFLOW_FILE, "r") as f:
            data = json.load(f)


        print("\n⚡ SAVED WORKFLOWS")


        for index, workflow in enumerate(data, 1):

            print("\n", index, ".", workflow["name"])
            print("Steps:", workflow["steps"])
            print("Created:", workflow["created"])


    except:

        print("❌ No workflows available")



def create_workflow():

    name = input("\nEnter workflow name: ")

    steps = []


    print("\nAdd workflow steps")
    print("Type 'done' to finish")


    while True:

        step = input("Step: ")


        if step.lower() == "done":

            break


        steps.append(step)


    save_workflow(name, steps)



# =====================================
# REAL AUTOMATION ENGINE v2.8
# =====================================

def run_workflow():

    create_folder()


    try:

        with open(WORKFLOW_FILE, "r") as f:
            data = json.load(f)


    except:

        print("❌ No workflows found")

        return



    print("\n⚡ AVAILABLE WORKFLOWS")


    for index, workflow in enumerate(data, 1):

        print(index, ".", workflow["name"])



    choice = int(input("\nSelect workflow: "))


    selected = data[choice - 1]


    print("\n🚀 EXECUTING:", selected["name"])



    for step in selected["steps"]:


        print("\n▶ Running:", step)



        if "story" in step.lower():

            stories.auto_create_story(
                "META ALPHA Generated Story",
                "Sci-Fi",
                "A futuristic AI war where humans and machines fight for control."
            )



        elif "character" in step.lower():

            print("👥 Character generation module ready")



        elif "prompt" in step.lower():

            prompts.auto_create_prompt(
                "META ALPHA Cinematic Prompt",
                "Video",
                "A futuristic city with advanced AI machines and cinematic lighting."
            )



        elif "save" in step.lower():

            files.auto_save_project(
                "META_ALPHA_Project",
                "META ALPHA Creation\n\nGenerated by BOBBY AI STUDIO v2.8"
            )



        else:

            print("⚙️ Task processed")



    print("\n🎉 WORKFLOW AUTOMATION COMPLETED!")